package Etapes;


import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.event.ActionEvent;

public class EtapesController {
	@FXML
	private Button precedent;
	@FXML
	private Button suivant;
	@FXML
	private Button retour;

	ModèleEtapes mdl;

	public EtapesController(ModèleEtapes mdl) {
		this.mdl = mdl;
	}

	// Event Listener on Button[#precedent].onAction
	@FXML
	public void clickOnPrecedent(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#suivant].onAction
	@FXML
	public void clickOnSuivant(ActionEvent event) {
		// TODO Autogenerated
	}
	@FXML
	public void backToAccueilRecette(ActionEvent event) {
		this.mdl.goToAccueil();
	}

}
